'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { RecoilRoot } from "recoil";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <RecoilRoot>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </RecoilRoot>
    </SessionWrapper>
  );
}
